# Collector specific configuration
base_url: https://www.transparency.org/en/api/latest/cpi
description: Corruption Perceptions Index score and rank for (country)
description_global: Corruption Perceptions Index scores and ranks for all countries
title: Corruption Perceptions Index
tags:
  - development
  - economics
  - environment
  - poverty
  - socioeconomics
